# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed13044728a86ea3837bcbcf2897c926fd76961c2288e76f8de6370a9ec74d69b1fbd9d1dc4c567027c7c7990a9f89261f3d5fe4d3b321be98fca1e7c79fee80

test:
  secret_key_base: 890a8972308175a397cbf537e24b3f0c6924d3b099058591f84a61bbba68328e8281fcc165db2a18ab4234dce47c32f56afd5ae421f9f3bf6e3a3258ae998b76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
